name: CI Automatic Notification and Test Owner Assignment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  process-pr:
    name: Process Pull Request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests with pytest
        run: |
          pytest tests/ --maxfail=3 --disable-warnings -q
      
      - name: Check for critical file changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            critical:
              - 'setup.py'
              - 'run.py'
              - 'backend/app.py'
              - 'backend/main.py'
      
      - name: Notify test owners about critical changes
        if: steps.filter.outputs.critical == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const testOwners = ['${{ vars.TEST_OWNER_1 }}', '${{ vars.TEST_OWNER_2 }}'].filter(owner => owner);
            
            if (testOwners.length === 0) {
              console.log('No test owners configured. Skipping notification.');
              return;
            }
            
            const changedFiles = [];
            if ('${{ contains(github.event.pull_request.body, 'setup.py') }}' === 'true') changedFiles.push('setup.py');
            if ('${{ contains(github.event.pull_request.body, 'run.py') }}' === 'true') changedFiles.push('run.py');
            if ('${{ contains(github.event.pull_request.body, 'backend/app.py') }}' === 'true') changedFiles.push('backend/app.py');
            
            const message = `## ⚠️ Critical Files Changed\n\n` +
                           `This PR contains changes to files that may require test updates:\n` +
                           `${changedFiles.map(file => `- \`${file}\``).join('\n')}\n\n` +
                           `${testOwners.map(owner => `@${owner}`).join(' ')} please review these changes and update tests if necessary.`;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
